# Generated by Django 2.1.3 on 2018-12-01 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.CreateModel(
            name='CourseOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('click_num', models.IntegerField(default=0)),
                ('favorite_num', models.IntegerField(default=0)),
                ('image', models.ImageField(default='organization/default.png', upload_to='organization/%Y/%M')),
                ('address', models.CharField(max_length=150)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.City')),
            ],
            options={
                'verbose_name': 'courseOrganization',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('work_years', models.IntegerField(default=0)),
                ('company', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=20)),
                ('points', models.CharField(max_length=50)),
                ('click_num', models.IntegerField(default=0)),
                ('favorite_num', models.IntegerField(default=0)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.CourseOrganization')),
            ],
        ),
    ]
