# Generated by Django 2.0 on 2018-12-01 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'city', 'verbose_name_plural': 'city'},
        ),
        migrations.AlterModelOptions(
            name='courseorganization',
            options={'verbose_name': 'courseOrganization', 'verbose_name_plural': 'courseOrganization'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'teacher', 'verbose_name_plural': 'teacher'},
        ),
    ]
