# Generated by Django 2.0 on 2018-12-01 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'course', 'verbose_name_plural': 'course'},
        ),
        migrations.AlterModelOptions(
            name='courseresource',
            options={'verbose_name': 'courseResource', 'verbose_name_plural': 'courseResource'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'lesson', 'verbose_name_plural': 'lesson'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'video', 'verbose_name_plural': 'video'},
        ),
    ]
