# Generated by Django 2.0 on 2018-12-01 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20181130_2309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecomment',
            options={'verbose_name': 'courseComment', 'verbose_name_plural': 'courseComment'},
        ),
        migrations.AlterModelOptions(
            name='userask',
            options={'verbose_name': 'userAsk', 'verbose_name_plural': 'userAsk'},
        ),
        migrations.AlterModelOptions(
            name='usercourse',
            options={'verbose_name': 'userCourse', 'verbose_name_plural': 'userCourse'},
        ),
        migrations.AlterModelOptions(
            name='userfavorite',
            options={'verbose_name': 'userFavorite', 'verbose_name_plural': 'userFavorite'},
        ),
        migrations.AlterModelOptions(
            name='usermessage',
            options={'verbose_name': 'userMessage', 'verbose_name_plural': 'userMessage'},
        ),
    ]
