# Generated by Django 2.0 on 2018-12-04 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20181201_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', 'register'), ('forget', 'reset_password'), ('update_email', 'update_email')], max_length=30),
        ),
    ]
